from tests.authors import AuthorTest
from tests.interpreters import InterpreterTest
from tests.users import UserTest
from tests.songs import SongTest
from tests.queries import QueryTest
from tests.exports import ExportTest
from tests.variants import SongVariantTest
from tests.songbooks import SongbookTest
from tests.translator import TranslatorTest
