class Events(object):
    AUTHOR_NEW = 'AUTHOR NEW'
    AUTHOR_EDIT = 'AUTHOR EDIT'
    AUTHOR_DELETE = 'AUTHOR DELETE'

    INTERPRETER_NEW = 'INTERPRETER NEW'
    INTERPRETER_EDIT = 'INTERPRETER EDIT'
    INTERPRETER_DELETE = 'INTERPRETER DELETE'

    SONG_NEW = 'SONG NEW'
    SONG_EDIT = 'SONG EDIT'
    SONG_DELETE = 'SONG DELETE'

    VARIANT_NEW = 'VARIANT NEW'
    VARIANT_EDIT = 'VARIANT EDIT'
    VARIANT_DELETE = 'VARIANT DELETE'

    SONGBOOK_NEW = 'SONGBOOK NEW'
    SONGBOOK_EDIT = 'SONGBOOK EDIT'
    SONGBOOK_DELETE = 'SONGBOOK DELETE'
    SONGBOOK_SET_SONG = 'SONGBOOK SET SONG'
    SONGBOOK_REMOVE_SONG = 'SONGBOOK REMOVE SONG'


EVENTS = Events()


class Permissions(object):
    PRIVATE = 'private'
    UNIT = 'unit'
    PUBLIC = 'public'


PERMISSION = Permissions()

permission_dict = [PERMISSION.PRIVATE, PERMISSION.UNIT, PERMISSION.PUBLIC]
